### ISSUE TITLE
Error in tf2_geometry_msgs.h

### ISSUE THREAD

**Issue by rvipin17** [ros/geometry2#334] opened 2018-10-09 09:17 UTC
`In file included from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:39:0:
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1009:55: error: ‘array’ is not a member of ‘std’
 geometry_msgs::WrenchStamped toMsg(const tf2::Stamped<std::array<tf2::Vector3, 
                                                       ^
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1009:55: note: suggested alternative:
In file included from /opt/ros/kinetic/include/ros/serialization.h:45:0,
                 from /opt/ros/kinetic/include/geometry_msgs/Point.h:14,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/include/costmap_2d/observation.h:35,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/include/costmap_2d/observation_buffer.h:44,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:37:
/usr/include/boost/array.hpp:60:11: note:   ‘boost::array’
     class array {
           ^
In file included from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:39:0:
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1009:55: error: ‘array’ is not a member of ‘std’
 geometry_msgs::WrenchStamped toMsg(const tf2::Stamped<std::array<tf2::Vector3, 
                                                       ^
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1009:55: note: suggested alternative:
In file included from /opt/ros/kinetic/include/ros/serialization.h:45:0,
                 from /opt/ros/kinetic/include/geometry_msgs/Point.h:14,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/include/costmap_2d/observation.h:35,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/include/costmap_2d/observation_buffer.h:44,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:37:
/usr/include/boost/array.hpp:60:11: note:   ‘boost::array’
     class array {
           ^
In file included from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:39:0:
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1009:81: error: spurious ‘>>’, use ‘>’ to terminate a template argument list
 s::WrenchStamped toMsg(const tf2::Stamped<std::array<tf2::Vector3, 2>>& in, geo
                                                                     ^
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1009:81: error: wrong number of template arguments (2, should be 1)
In file included from /home/addverb/catkin_ws/src/geometry2/tf2_ros/include/tf2_ros/buffer_interface.h:36:0,
                 from /home/addverb/catkin_ws/src/geometry2/tf2_ros/include/tf2_ros/buffer.h:35,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/include/costmap_2d/observation_buffer.h:45,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:37:
/home/addverb/catkin_ws/src/geometry2/tf2/include/tf2/transform_datatypes.h:44:7: note: provided for ‘template<class T> class tf2::Stamped’
 class Stamped : public T{
       ^
In file included from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:39:0:
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1009:55: error: ‘array’ is not a member of ‘std’
 geometry_msgs::WrenchStamped toMsg(const tf2::Stamped<std::array<tf2::Vector3, 
                                                       ^
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1009:55: note: suggested alternative:
In file included from /opt/ros/kinetic/include/ros/serialization.h:45:0,
                 from /opt/ros/kinetic/include/geometry_msgs/Point.h:14,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/include/costmap_2d/observation.h:35,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/include/costmap_2d/observation_buffer.h:44,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:37:
/usr/include/boost/array.hpp:60:11: note:   ‘boost::array’
     class array {
           ^
In file included from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:39:0:
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1009:55: error: ‘array’ is not a member of ‘std’
 geometry_msgs::WrenchStamped toMsg(const tf2::Stamped<std::array<tf2::Vector3, 
                                                       ^
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1009:55: note: suggested alternative:
In file included from /opt/ros/kinetic/include/ros/serialization.h:45:0,
                 from /opt/ros/kinetic/include/geometry_msgs/Point.h:14,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/include/costmap_2d/observation.h:35,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/include/costmap_2d/observation_buffer.h:44,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:37:
/usr/include/boost/array.hpp:60:11: note:   ‘boost::array’
     class array {
           ^
In file included from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:39:0:
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1009:81: error: spurious ‘>>’, use ‘>’ to terminate a template argument list
 s::WrenchStamped toMsg(const tf2::Stamped<std::array<tf2::Vector3, 2>>& in, geo
                                                                     ^
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1009:81: error: wrong number of template arguments (2, should be 1)
In file included from /home/addverb/catkin_ws/src/geometry2/tf2_ros/include/tf2_ros/buffer_interface.h:36:0,
                 from /home/addverb/catkin_ws/src/geometry2/tf2_ros/include/tf2_ros/buffer.h:35,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/include/costmap_2d/observation_buffer.h:45,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:37:
/home/addverb/catkin_ws/src/geometry2/tf2/include/tf2/transform_datatypes.h:44:7: note: provided for ‘template<class T> class tf2::Stamped’
 class Stamped : public T{
       ^
In file included from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:39:0:
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1009:55: error: ‘array’ is not a member of ‘std’
 geometry_msgs::WrenchStamped toMsg(const tf2::Stamped<std::array<tf2::Vector3, 
                                                       ^
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1009:55: note: suggested alternative:
In file included from /opt/ros/kinetic/include/ros/serialization.h:45:0,
                 from /opt/ros/kinetic/include/geometry_msgs/Point.h:14,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/include/costmap_2d/observation.h:35,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/include/costmap_2d/observation_buffer.h:44,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:37:
/usr/include/boost/array.hpp:60:11: note:   ‘boost::array’
     class array {
           ^
In file included from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:39:0:
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1009:55: error: ‘array’ is not a member of ‘std’
 geometry_msgs::WrenchStamped toMsg(const tf2::Stamped<std::array<tf2::Vector3, 
                                                       ^
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1009:55: note: suggested alternative:
In file included from /opt/ros/kinetic/include/ros/serialization.h:45:0,
                 from /opt/ros/kinetic/include/geometry_msgs/Point.h:14,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/include/costmap_2d/observation.h:35,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/include/costmap_2d/observation_buffer.h:44,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:37:
/usr/include/boost/array.hpp:60:11: note:   ‘boost::array’
     class array {
           ^
In file included from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:39:0:
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1009:81: error: spurious ‘>>’, use ‘>’ to terminate a template argument list
 s::WrenchStamped toMsg(const tf2::Stamped<std::array<tf2::Vector3, 2>>& in, geo
                                                                     ^
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1009:81: error: wrong number of template arguments (2, should be 1)
In file included from /home/addverb/catkin_ws/src/geometry2/tf2_ros/include/tf2_ros/buffer_interface.h:36:0,
                 from /home/addverb/catkin_ws/src/geometry2/tf2_ros/include/tf2_ros/buffer.h:35,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/include/costmap_2d/observation_buffer.h:45,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:37:
/home/addverb/catkin_ws/src/geometry2/tf2/include/tf2/transform_datatypes.h:44:7: note: provided for ‘template<class T> class tf2::Stamped’
 class Stamped : public T{
       ^
In file included from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:39:0:
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1009:55: error: ‘array’ is not a member of ‘std’
 geometry_msgs::WrenchStamped toMsg(const tf2::Stamped<std::array<tf2::Vector3, 
                                                       ^
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1009:55: note: suggested alternative:
In file included from /opt/ros/kinetic/include/ros/serialization.h:45:0,
                 from /opt/ros/kinetic/include/geometry_msgs/Point.h:14,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/include/costmap_2d/observation.h:35,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/include/costmap_2d/observation_buffer.h:44,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:37:
/usr/include/boost/array.hpp:60:11: note:   ‘boost::array’
     class array {
           ^
In file included from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:39:0:
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1009:55: error: ‘array’ is not a member of ‘std’
 geometry_msgs::WrenchStamped toMsg(const tf2::Stamped<std::array<tf2::Vector3, 
                                                       ^
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1009:55: note: suggested alternative:
In file included from /opt/ros/kinetic/include/ros/serialization.h:45:0,
                 from /opt/ros/kinetic/include/geometry_msgs/Point.h:14,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/include/costmap_2d/observation.h:35,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/include/costmap_2d/observation_buffer.h:44,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:37:
/usr/include/boost/array.hpp:60:11: note:   ‘boost::array’
     class array {
           ^
In file included from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:39:0:
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1009:81: error: spurious ‘>>’, use ‘>’ to terminate a template argument list
 s::WrenchStamped toMsg(const tf2::Stamped<std::array<tf2::Vector3, 2>>& in, geo
                                                                     ^
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1009:81: error: wrong number of template arguments (2, should be 1)
In file included from /home/addverb/catkin_ws/src/geometry2/tf2_ros/include/tf2_ros/buffer_interface.h:36:0,
                 from /home/addverb/catkin_ws/src/geometry2/tf2_ros/include/tf2_ros/buffer.h:35,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/include/costmap_2d/observation_buffer.h:45,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:37:
/home/addverb/catkin_ws/src/geometry2/tf2/include/tf2/transform_datatypes.h:44:7: note: provided for ‘template<class T> class tf2::Stamped’
 class Stamped : public T{
       ^
In file included from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:39:0:
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1009:42: error: invalid use of template-name ‘tf2::Stamped’ without an argument list
 geometry_msgs::WrenchStamped toMsg(const tf2::Stamped<std::array<tf2::Vector3, 
                                          ^
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1009:54: error: expected ‘,’ or ‘...’ before ‘<’ token
 geometry_msgs::WrenchStamped toMsg(const tf2::Stamped<std::array<tf2::Vector3, 
                                                      ^
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h: In function ‘geometry_msgs::WrenchStamped tf2::toMsg(int)’:
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1011:3: error: ‘out’ was not declared in this scope
   out.header.stamp = in.stamp_;
   ^
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1011:22: error: ‘in’ was not declared in this scope
   out.header.stamp = in.stamp_;
                      ^
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h: At global scope:
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1020:68: error: ‘array’ is not a member of ‘std’
 void fromMsg(const geometry_msgs::WrenchStamped& msg, tf2::Stamped<std::array<t
                                                                    ^
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1020:68: note: suggested alternative:
In file included from /opt/ros/kinetic/include/ros/serialization.h:45:0,
                 from /opt/ros/kinetic/include/geometry_msgs/Point.h:14,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/include/costmap_2d/observation.h:35,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/include/costmap_2d/observation_buffer.h:44,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:37:
/usr/include/boost/array.hpp:60:11: note:   ‘boost::array’
     class array {
           ^
In file included from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:39:0:
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1020:68: error: ‘array’ is not a member of ‘std’
 void fromMsg(const geometry_msgs::WrenchStamped& msg, tf2::Stamped<std::array<t
                                                                    ^
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1020:68: note: suggested alternative:
In file included from /opt/ros/kinetic/include/ros/serialization.h:45:0,
                 from /opt/ros/kinetic/include/geometry_msgs/Point.h:14,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/include/costmap_2d/observation.h:35,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/include/costmap_2d/observation_buffer.h:44,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:37:
/usr/include/boost/array.hpp:60:11: note:   ‘boost::array’
     class array {
           ^
In file included from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:39:0:
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1020:94: error: spurious ‘>>’, use ‘>’ to terminate a template argument list
 metry_msgs::WrenchStamped& msg, tf2::Stamped<std::array<tf2::Vector3, 2>>& out)
                                                                        ^
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1020:94: error: wrong number of template arguments (2, should be 1)
In file included from /home/addverb/catkin_ws/src/geometry2/tf2_ros/include/tf2_ros/buffer_interface.h:36:0,
                 from /home/addverb/catkin_ws/src/geometry2/tf2_ros/include/tf2_ros/buffer.h:35,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/include/costmap_2d/observation_buffer.h:45,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:37:
/home/addverb/catkin_ws/src/geometry2/tf2/include/tf2/transform_datatypes.h:44:7: note: provided for ‘template<class T> class tf2::Stamped’
 class Stamped : public T{
       ^
In file included from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:39:0:
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1020:68: error: ‘array’ is not a member of ‘std’
 void fromMsg(const geometry_msgs::WrenchStamped& msg, tf2::Stamped<std::array<t
                                                                    ^
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1020:68: note: suggested alternative:
In file included from /opt/ros/kinetic/include/ros/serialization.h:45:0,
                 from /opt/ros/kinetic/include/geometry_msgs/Point.h:14,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/include/costmap_2d/observation.h:35,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/include/costmap_2d/observation_buffer.h:44,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:37:
/usr/include/boost/array.hpp:60:11: note:   ‘boost::array’
     class array {
           ^
In file included from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:39:0:
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1020:68: error: ‘array’ is not a member of ‘std’
 void fromMsg(const geometry_msgs::WrenchStamped& msg, tf2::Stamped<std::array<t
                                                                    ^
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1020:68: note: suggested alternative:
In file included from /opt/ros/kinetic/include/ros/serialization.h:45:0,
                 from /opt/ros/kinetic/include/geometry_msgs/Point.h:14,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/include/costmap_2d/observation.h:35,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/include/costmap_2d/observation_buffer.h:44,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:37:
/usr/include/boost/array.hpp:60:11: note:   ‘boost::array’
     class array {
           ^
In file included from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:39:0:
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1020:94: error: spurious ‘>>’, use ‘>’ to terminate a template argument list
 metry_msgs::WrenchStamped& msg, tf2::Stamped<std::array<tf2::Vector3, 2>>& out)
                                                                        ^
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1020:94: error: wrong number of template arguments (2, should be 1)
In file included from /home/addverb/catkin_ws/src/geometry2/tf2_ros/include/tf2_ros/buffer_interface.h:36:0,
                 from /home/addverb/catkin_ws/src/geometry2/tf2_ros/include/tf2_ros/buffer.h:35,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/include/costmap_2d/observation_buffer.h:45,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:37:
/home/addverb/catkin_ws/src/geometry2/tf2/include/tf2/transform_datatypes.h:44:7: note: provided for ‘template<class T> class tf2::Stamped’
 class Stamped : public T{
       ^
In file included from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:39:0:
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1020:60: error: ‘tf2::Stamped’ is not a type
 void fromMsg(const geometry_msgs::WrenchStamped& msg, tf2::Stamped<std::array<t
                                                            ^
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1020:67: error: expected ‘,’ or ‘...’ before ‘<’ token
 void fromMsg(const geometry_msgs::WrenchStamped& msg, tf2::Stamped<std::array<t
                                                                   ^
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h: In function ‘void tf2::fromMsg(const WrenchStamped&, int)’:
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1022:3: error: ‘out’ was not declared in this scope
   out.stamp_ = msg.header.stamp;
   ^
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1028:3: error: ‘array’ is not a member of ‘std’
   std::array<tf2::Vector3, 2> tmp_array;
   ^
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1028:3: note: suggested alternative:
In file included from /opt/ros/kinetic/include/ros/serialization.h:45:0,
                 from /opt/ros/kinetic/include/geometry_msgs/Point.h:14,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/include/costmap_2d/observation.h:35,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/include/costmap_2d/observation_buffer.h:44,
                 from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:37:
/usr/include/boost/array.hpp:60:11: note:   ‘boost::array’
     class array {
           ^
In file included from /home/addverb/catkin_ws/src/navigation/costmap_2d/src/observation_buffer.cpp:39:0:
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1028:26: error: expected primary-expression before ‘,’ token
   std::array<tf2::Vector3, 2> tmp_array;
                          ^
/home/addverb/catkin_ws/src/geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:1028:31: error: ‘tmp_array’ was not declared in this scope
   std::array<tf2::Vector3, 2> tmp_array;
                               ^
navigation/costmap_2d/CMakeFiles/costmap_2d.dir/build.make:110: recipe for target 'navigation/costmap_2d/CMakeFiles/costmap_2d.dir/src/observation_buffer.cpp.o' failed
make[2]: *** [navigation/costmap_2d/CMakeFiles/costmap_2d.dir/src/observation_buffer.cpp.o] Error 1
CMakeFiles/Makefile2:36675: recipe for target 'navigation/costmap_2d/CMakeFiles/costmap_2d.dir/all' failed
make[1]: *** [navigation/costmap_2d/CMakeFiles/costmap_2d.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed
`
I cloned geometry2 into my catkin workspace and after catkin_make, receiving the above error. Any idea how to fix this?

**Comment by tfoote** [comment] 2018-10-11 02:12
Please clarify how to reproduce your workspace including what system you're running on, what packages you have installed from binaries, and where you got them from and what source checkouts you have in your workspace including the branch.

**Comment by Master-Matt** [comment] 2018-11-02 15:14
I just got this error too. I was trying to use navigation from source, but then it required me to use tf2_sensor_msgs from source. I cloned the indigo-devel branch for working on kinetic. I had both of these binary installed before. Do you need to remove them before installing these from source? 
I'm wondering if it's a compiler version issue, because in C11 array is part of std, but the errors say it is not a part of std.

*EDIT*
solved this by adding

add_compile_options(-std=c++11)

to the cmakelists of the packages that required use of tf2_geometry_msgs

**Comment by tfoote** [comment] 2018-11-02 18:49
Yes if you change the target platforms for different branches you may need to update compiler flags. In particular Indigo expects C++03 while Kinetic expects C++11 as the minimum requirement. See REP 3 for more details: http://www.ros.org/reps/rep-0003.html#indigo-igloo-may-2014

Since there's no reply from the original poster and a reproduction of the issue has found a workaround, I'm going to close this.

**Closed as completed by tfoote** 2018-11-02 18:49 UTC
