### ISSUE TITLE
tf2_tools echo.py use wrong terminology for source and target frame.

### ISSUE THREAD

**Issue by Hugal31** [ros/geometry2#510] opened 2021-05-11 14:46 UTC
echo.py takes the arguments "source_frame" and "target_frame" in this order. [Further in the loop][echo.py call], it calls [`tf2_ros.Buffer.lookup_transform`][Buffer.lookup_transform] by passing `source_frame`, then `target_frame`, whereas the argument order for `lookup_transform` is target_frame then source_frame.

This is coherent with the `tf echo` script, but is not with the rest of tf and tf2 terminology, or at least the API terminology. This can (and has) lead to confusion.

I suggest to rename the two arguments so the API remains compatible. Also, providing some documentation for the command line would be nice.

[Buffer.lookup_transform]: https://github.com/ros/geometry2/blob/c73b5939723db078c9bbe18523230ad54f859682/tf2_ros/src/tf2_ros/buffer.py#L73
[echo.py call]: https://github.com/ros/geometry2/blob/c73b5939723db078c9bbe18523230ad54f859682/tf2_tools/scripts/echo.py#L170

**Comment by tfoote** [comment] 2021-05-14 22:14
Duplicate of https://github.com/ros/geometry/issues/226 https://github.com/ros/geometry/issues/111 and https://github.com/ros/geometry/issues/108

**Closed as completed by tfoote** 2021-05-14 22:14 UTC
